# Generated by Django 4.2.7 on 2023-11-26 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_id", models.CharField(blank=True, max_length=255, unique=True)),
                ("team_name", models.CharField(blank=True, max_length=255, null=True)),
                ("team_logo", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "selected_console",
                    models.CharField(
                        blank=True,
                        choices=[("Xbox", "Xbox"), ("Playstation", "Playstation")],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "points_per_game",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        default=0.0,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "assists_per_game",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        default=0.0,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "rebounds_per_game",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        default=0.0,
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("wins", models.IntegerField(blank=True, default=0, null=True)),
                ("loss", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "team_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "member_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_member",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_team",
                        to="teams.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LineUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_lineups",
                        to="teams.team",
                    ),
                ),
            ],
        ),
    ]
