# Generated by Django 4.2.7 on 2023-11-26 07:45

from django.db import migrations, models
import teams.models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_team_created_at_team_team_about_team_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="team_logo",
            field=models.ImageField(
                blank=True, null=True, upload_to=teams.models.upload_image_path
            ),
        ),
    ]
