# Generated by Django 4.2.7 on 2023-11-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0007_event_event_description"),
        ("teams", "0003_alter_team_team_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="team_events",
            field=models.ManyToManyField(
                blank=True, related_name="team_events", to="events.event"
            ),
        ),
    ]
