# Generated by Django 4.2.7 on 2023-11-26 07:57

from django.db import migrations, models
import django.db.models.deletion
import teams.models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0004_team_team_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=teams.models.upload_gallery_path,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_gallery",
                        to="teams.team",
                    ),
                ),
            ],
        ),
    ]
