# Generated by Django 4.2.7 on 2023-11-26 08:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teams", "0006_teamschedule"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LineUp",
            new_name="TeamLineUp",
        ),
    ]
