# Generated by Django 4.2.7 on 2023-12-01 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_rename_lineup_teamlineup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_events',
        ),
    ]
