# Generated by Django 4.2.7 on 2023-12-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_remove_team_team_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='selected_console',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
