# Generated by Django 4.2.7 on 2023-12-01 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_alter_team_selected_console'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='selected_console',
            new_name='selected_consoles',
        ),
    ]
