# Generated by Django 4.2.7 on 2023-12-01 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('card_number', models.CharField(blank=True, max_length=255, null=True)),
                ('expiry_month', models.CharField(blank=True, max_length=255, null=True)),
                ('expiry_year', models.CharField(blank=True, max_length=255, null=True)),
                ('cvc', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_type', models.CharField(blank=True, choices=[('Stripe', 'Stripe'), ('Paypal', 'Paypal')], max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
