# Generated by Django 4.2.7 on 2023-12-01 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_event_sign_up_fee'),
        ('teams', '0010_rename_selected_console_team_selected_consoles'),
        ('payments', '0002_rename_payments_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_payments', to='events.event'),
        ),
        migrations.AddField(
            model_name='payment',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_payments', to='teams.team'),
        ),
    ]
