# Generated by Django 4.2.7 on 2023-11-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connects", "0002_rename_game_tag_connect_gamer_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connect",
            name="connect_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PSN", "PSN"),
                    ("Xbox Live", "Xbox Live"),
                    ("Twitter", "Twitter"),
                    ("Discord", "Discord"),
                    ("Twitch", "Twitch"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
