# Generated by Django 4.2.7 on 2023-11-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_event_event_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[("Season", "Season"), ("Tournament", "Tournament")],
                max_length=255,
                null=True,
            ),
        ),
    ]
