# Generated by Django 4.2.7 on 2023-11-26 06:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0004_event_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_sign_ups",
            field=models.ManyToManyField(
                blank=True, related_name="event_signups", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
