# Generated by Django 4.2.7 on 2023-11-26 06:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0005_event_event_sign_ups"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_teams",
            field=models.ManyToManyField(
                blank=True, related_name="event_teams", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
