# Generated by Django 4.2.7 on 2023-11-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0006_event_event_teams"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
