# Generated by Django 4.2.7 on 2023-11-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0009_event_league_alter_event_event_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
