# Generated by Django 4.2.7 on 2023-11-26 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0010_league_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="league",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="league_events",
                to="events.league",
            ),
        ),
    ]
