# Generated by Django 4.2.7 on 2023-11-26 16:58

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0011_alter_event_league"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="league_cover",
            field=models.ImageField(
                blank=True, null=True, upload_to=events.models.upload_image_path
            ),
        ),
    ]
