# Generated by Django 4.2.7 on 2023-11-26 17:07

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0013_league_draft_leagues_league_seasons_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_cover",
            field=models.ImageField(
                blank=True, null=True, upload_to=events.models.upload_event_image_path
            ),
        ),
    ]
