# Generated by Django 4.2.7 on 2023-11-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0014_event_event_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_consoles",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
