# Generated by Django 4.2.7 on 2023-12-01 04:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0016_remove_event_event_sign_ups_remove_event_event_teams_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsignup',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='event_team_players', to=settings.AUTH_USER_MODEL),
        ),
    ]
