# Generated by Django 4.2.7 on 2023-12-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_alter_eventsignup_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sign_up_fee',
            field=models.CharField(blank=True, default='0000', max_length=255, null=True),
        ),
    ]
