version: "3.8"
services:

  # Redis
  redis:
    image: redis:alpine
    container_name: redis_d

  # Database Postgres
  api-unifiedpro-db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    #build: .
    environment:
      - POSTGRES_DB=unifiedpro_am_proj
      - POSTGRES_USER=unifiedpro_am_proj
      - POSTGRES_PASSWORD=unifiedpro_am_proj
    ports:
      - "54322:5432"
    #container_name: postgres_db_d

  # Django Application
  api-unifiedpro-app:
    image: api-unifiedpro-app:django
    build: .
    volumes:
      - .:/django4
      - ./static_cdn:/var/lib/static_cdn
    ports:
      - "8484:8484"
    #container_name: django4_app
    command: python manage.py runserver 0.0.0.0:8484
    depends_on:
      - api-unifiedpro-db

  # Celery Worker
  celery:
    restart: always
    build:
      context: .
    command: celery -A unifiedpro_am_proj worker -l DEBUG
    volumes:
      - .:/django4
    container_name: celery_d
    depends_on:
      - api-unifiedpro-db
      - redis
      - api-unifiedpro-app

  # Celery Beat
  celery-beat:
    restart: always
    build:
      context: .
    command: celery -A unifiedpro_am_proj beat -l DEBUG
    volumes:
      - .:/django4
    container_name: celery_beat_d
    depends_on:
      - api-unifiedpro-db
      - redis
      - api-unifiedpro-app

volumes:
  static_cdn:


#networks:
# default:
#    external: true
#    name: docker-nginx-proxy-manager

