# Generated by Django 4.2.7 on 2023-11-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Point Guard", "Point Guard"),
                    ("Shooting Guard", "Shooting Guard"),
                    ("Small Forward", "Small Forward"),
                    ("Power Forward", "Power Forward"),
                    ("Center", "Center"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
