# Generated by Django 4.2.7 on 2023-11-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_user_country_remove_user_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_online",
            field=models.BooleanField(default=True),
        ),
    ]
