# Generated by Django 4.2.7 on 2023-11-21 07:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0002_userprofile_country_alter_userprofile_position"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="connects",
        ),
    ]
