# Generated by Django 4.2.7 on 2023-11-26 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0003_remove_userprofile_connects"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="assists_per_game",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0.0, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="points_per_game",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0.0, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="rebounds_per_game",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0.0, max_digits=5, null=True
            ),
        ),
    ]
