# Generated by Django 4.2.7 on 2023-11-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0004_userprofile_assists_per_game_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="games_lost",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="games_played",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="games_won",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
