# Generated by Django 4.2.7 on 2023-11-26 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("teams", "0007_rename_lineup_teamlineup"),
        ("events", "0015_event_event_consoles"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team_1_avg_score",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "team_1_1st_quart",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "team_1_2nd_quart",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "team_1_3rd_quart",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "team_1_4th_quart",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "team_1_overtime",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "team_2_avg_score",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "team_2_1st_quart",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "team_2_2nd_quart",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "team_2_3rd_quart",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "team_2_4th_quart",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "team_2_overtime",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_games",
                        to="events.event",
                    ),
                ),
                (
                    "team_1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_team_1",
                        to="teams.team",
                    ),
                ),
                (
                    "team_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_team_2",
                        to="teams.team",
                    ),
                ),
            ],
        ),
    ]
